stages:
  data_ingestion:
    cmd: python src/stage_01_data_ingestion.py
    deps:
      - src/pipeline/training_pipeline.py
      - src/components/data_ingestion.py
      - src/entity/config_entity.py
    outs:
      - artifact/data_ingestion
      - artifact/artifact_objects/data_ingestion.pkl
      
  data_validation:
    cmd: python src/stage_02_data_validation.py
    deps:
      - src/pipeline/training_pipeline.py
      - src/components/data_validation.py
      - src/entity/config_entity.py
    outs:
      - artifact/data_validation
      - artifact/artifact_objects/data_validation.pkl


  data_transformation:
    cmd: python src/stage_03_data_transformation.py
    deps:
      - src/pipeline/training_pipeline.py
      - src/components/data_transformation.py
      - src/entity/config_entity.py
    outs:
      - artifact/data_transformation
      - artifact/artifact_objects/data_transformation.pkl

  # model_trainer:
  #   cmd: python src/stage_04_model_trainer.py
  #   deps:
  #     - src/pipeline/training_pipeline.py
  #     - src/components/model_trainer.py
  #     - src/entity/config_entity.py
  #   outs:
  #     - artifact/model_trainer
  #     - artifact/artifact_objects/model_trainer.pkl
